security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email  

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            # Enable form_login
            form_login:
                login_path: login          
                check_path: login_check    
                default_target_path: home  

            # Enable logout
            logout:
                path: logout
                target: home

            # Enable security
            security: true

    access_control:
        - { path: ^/utilisateur/\d+/edit, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/utilisateur, roles: ROLE_ADMIN }
        - { path: ^/commentaire$, roles: ROLE_ADMIN }
        - { path: ^/produit$, roles: ROLE_ADMIN }
        - { path: ^/category, roles: ROLE_ADMIN }
        # - { path: ^/shop$, roles: ROLE_ADMIN }
