security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email  # Assuming you're using email for login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # Enable form_login
            form_login:
                login_path: login          # Route for displaying the login form
                check_path: login_check    # Route for processing the form submission
                default_target_path: home  # Redirect to home after login (adjust as needed)

            # Enable logout
            logout:
                path: logout
                target: login # Redirect after logout (optional)

            # Enable security
            security: true

    # Access control
    # access_control:
    #     - { path: ^/admin, roles: ROLE_ADMIN }  # Example for securing admin routes
    #     - { path: ^/profile, roles: ROLE_USER }
